#!/bin/sh
set -Ceu
step=${STEP:-stepA_mal}.ck

regex_chugin=${REGEX_CHUGIN:-/usr/local/lib/chuck/1.5.2.5/RegEx.chug}
if [ ! -f "$regex_chugin" ]; then
    echo 'Set $REGEX_CHUGIN to the absolute path of RegEx.chug'
    exit 1
fi

# The globs will be expanded in the exec line.
imports=$(sed -n "s|^ *// *@import *||p" $step)

separator=$(printf '\a')
for x; do
    CHUCK_ARGS="${CHUCK_ARGS:+$CHUCK_ARGS$separator}$x"
done
export CHUCK_ARGS

exec chuck --caution-to-the-wind --silent --chugin:"$regex_chugin" \
     $imports $step
