#!/bin/sh
set -Cefu
case ${haxe_MODE:-neko} in
    neko)   exec neko    ${STEP:-stepA_mal}.n   "$@" ;;
    python) exec python3 ${STEP:-stepA_mal}.py  "$@" ;;
    js)     exec node    ${STEP:-stepA_mal}.js  "$@" ;;
    cpp)    exec         cpp/${STEP:-stepA_mal} "$@" ;;
    *) echo "Invalid haxe_MODE: $haxe_MODE"; exit 2 ;;
esac
