#!/bin/sh

for x; do
    args="${args:+$args, }'$x'"
done
prompt="${STEP:-stepA_mal}(${args:-});quit;"

case ${matlab_MODE:-octave} in
    matlab)
        exec matlab -nodisplay -nosplash -nodesktop -nojvm -r "$prompt"
        ;;
    octave)
        exec octave -q --no-gui --no-history --eval "$prompt"
        ;;
    *)
        echo "Bad matlab_MODE: $matlab_MODE"
        exit 1
        ;;
esac
