#!/usr/bin/env bash
cd $(dirname $0)
{
    printf '(def! -*ARGS*- (list'
    [ $# = 0 ] || printf ' "%s"' "$@"
    echo '))'
} > .args.mal
case ${basic_MODE:-cbm} in
    cbm)    exec cbmbasic ${STEP:-stepA_mal}.bas "$@" ;;
    qbasic) exec ./${STEP:-stepA_mal} "$@" ;;
    *)      echo "Invalid basic_MODE: $basic_MODE"; exit 2 ;;
esac
