#!/usr/bin/env bash
export PATH="$PATH:$(dirname $0)/node_modules/.bin"
STEP=${STEP:-stepA_mal}
case ${clojure_MODE:-clj} in
    cljs) exec lumo -c $(dirname $0)/src -m mal.${STEP//_/-} "$@" ;;
    clj)  exec java -jar $(dirname $0)/target/$STEP.jar "$@" ;;
esac
echo "Invalid clojure_MODE: $clojure_MODE"
exit 1
