#!/bin/sh
set -Cefu
case ${wasm_MODE:-js} in
wasmtime)
    exec wasmtime --dir=./ --dir=../ --dir=/ ${STEP:-stepA_mal}.wasm "$@" ;;
wasmer)
    exec wasmer run --dir=./ --dir=../ --dir=/ ${STEP:-stepA_mal}.wasm -- "$@" ;;
warpy)
    exec warpy --argv --memory-pages 256 ${STEP:-stepA_mal}.wasm "$@" ;;
wax)
    exec wax ${STEP:-stepA_mal}.wasm "$@" ;;
wace_libc)
    exec wace ${STEP:-stepA_mal}.wasm "$@" ;;
wace_fooboot)
    echo >&2 "wace_fooboot mode not yet supported" ;;
node|js|*)
    exec node run.js ${STEP:-stepA_mal}.wasm "$@" ;;
esac
